---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: hands-on-lab
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:5.4.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"