apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: hands-on-lab
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    name: grafana
  type: NodePort